import type { TrackProject } from '../types';
import type { BuiltTrack, MeshData, Vec3 } from '../geometry';
import { THEME_PALETTES, meshColor } from '../state/project';

function fmt(n: number): string {
  return (Math.round(n * 1000) / 1000).toString();
}

function vertsPy(verts: Vec3[]): string {
  return '[' + verts.map((v) => `(${fmt(v[0])},${fmt(v[1])},${fmt(v[2])})`).join(',') + ']';
}

function facesPy(faces: [number, number, number][]): string {
  return '[' + faces.map((f) => `(${f[0]},${f[1]},${f[2]})`).join(',') + ']';
}

function hexRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  return [
    parseInt(h.slice(0, 2), 16) / 255,
    parseInt(h.slice(2, 4), 16) / 255,
    parseInt(h.slice(4, 6), 16) / 255,
  ];
}

// Generate the self-contained Blender FALLBACK script. The primary export is a
// ready-made FBX, but this lets a user rebuild it from scratch in Blender. It
// rebuilds the exact baked geometry, forces normals up, applies 1:1 scale,
// assigns a coloured material per surface, creates oriented empties, exports FBX.
export function genBlenderScript(project: TrackProject, built: BuiltTrack, slug: string): string {
  const pal = THEME_PALETTES[project.meta.theme];

  const meshBlocks = built.meshes
    .map((m: MeshData, i) => {
      const [r, g, b] = hexRgb(meshColor(m.name, pal));
      return `MESHES.append(dict(name="${m.name}", color=(${fmt(r)},${fmt(g)},${fmt(b)}), verts=${vertsPy(m.vertices)}, faces=${facesPy(m.faces)}))  # ${i}`;
    })
    .join('\n');

  const empties = built.empties
    .map((e) => {
      const r = e.basis;
      const p = e.position;
      return `  ("${e.name}", (${fmt(p[0])},${fmt(p[1])},${fmt(p[2])}), ((${fmt(r[0][0])},${fmt(r[0][1])},${fmt(r[0][2])}),(${fmt(r[1][0])},${fmt(r[1][1])},${fmt(r[1][2])}),(${fmt(r[2][0])},${fmt(r[2][1])},${fmt(r[2][2])}))),`;
    })
    .join('\n');

  return `# build_track.py  --  generated by AC Track Forge  (Blender FALLBACK exporter)
# Track: ${project.meta.name}  (${slug})
#
# You normally do NOT need this: the zip already contains ${slug}.fbx ready for
# KsEditor. Use this only if you want to rebuild the FBX from Blender.
#
# RUN: Blender -> Scripting -> Open this file -> Run Script. Writes ${slug}.fbx
# next to the script. Scale (1:1), normals (up), names, materials, and the
# spawn/timing empties are all already correct.

import bpy, bmesh, mathutils, os

TRACK_NAME = "${slug}"
MESHES = []
${meshBlocks}

EMPTIES = [
${empties}
]

def clear_scene():
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete(use_global=False)
    for coll in (bpy.data.meshes, bpy.data.materials):
        for b in list(coll):
            if b.users == 0:
                coll.remove(b)

def set_metric():
    sc = bpy.context.scene
    sc.unit_settings.system = 'METRIC'
    sc.unit_settings.scale_length = 1.0

def make_material(name, color):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = False
    mat.diffuse_color = (color[0], color[1], color[2], 1.0)
    return mat

def make_mesh(spec):
    mesh = bpy.data.meshes.new(spec["name"])
    obj = bpy.data.objects.new(spec["name"], mesh)
    bpy.context.collection.objects.link(obj)
    mesh.from_pydata(spec["verts"], [], spec["faces"])
    mesh.update()
    bm = bmesh.new(); bm.from_mesh(mesh)
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    if sum(f.normal.z for f in bm.faces) < 0:
        bmesh.ops.reverse_faces(bm, faces=bm.faces)
    bm.to_mesh(mesh); bm.free()
    mesh.update()
    obj.data.materials.append(make_material("mat_" + spec["name"], spec["color"]))
    obj.scale = (1.0, 1.0, 1.0)
    obj.rotation_euler = (0.0, 0.0, 0.0)
    return obj

def make_empty(name, pos, r):
    e = bpy.data.objects.new(name, None)
    e.empty_display_type = 'ARROWS'
    e.empty_display_size = 2.0
    bpy.context.collection.objects.link(e)
    e.matrix_world = mathutils.Matrix((
        (r[0][0], r[0][1], r[0][2], pos[0]),
        (r[1][0], r[1][1], r[1][2], pos[1]),
        (r[2][0], r[2][1], r[2][2], pos[2]),
        (0.0, 0.0, 0.0, 1.0),
    ))
    return e

def script_dir():
    try:
        return os.path.dirname(os.path.abspath(__file__))
    except NameError:
        pass
    if bpy.data.filepath:
        return os.path.dirname(bpy.data.filepath)
    return os.path.expanduser("~")

clear_scene()
set_metric()

objs = [make_mesh(m) for m in MESHES]
for name, pos, r in EMPTIES:
    make_empty(name, pos, r)

bpy.ops.object.select_all(action='DESELECT')
for o in objs:
    o.select_set(True)
bpy.context.view_layer.objects.active = objs[0]
bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)

out = os.path.join(script_dir(), TRACK_NAME + ".fbx")
bpy.ops.object.select_all(action='SELECT')
bpy.ops.export_scene.fbx(
    filepath=out, use_selection=False, apply_unit_scale=True, global_scale=1.0,
    apply_scale_options='FBX_SCALE_NONE', object_types={'MESH', 'EMPTY'},
    axis_forward='-Z', axis_up='Y', use_mesh_modifiers=True,
)
print("AC Track Forge: exported", out)
`;
}
