import type { TrackProject } from '../types';
import type { BuiltTrack, MeshData, Vec3, EmptyData } from '../geometry';
import { THEME_PALETTES, meshColor } from '../state/project';

// ---------------------------------------------------------------------------
// Direct ASCII FBX writer (tab-indented, FBX 7.4 — the conventional format the
// FBX SDK and tab-sensitive parsers expect). Produces a 1:1, normals-correct,
// materials-assigned FBX that KsEditor imports directly — no Blender needed.
// Our native frame is Z-up; FBX is Y-up, so we apply R:(x,y,z) -> (x, z, -y),
// a proper rotation (det +1) so winding/normals stay consistent.
// ---------------------------------------------------------------------------

function toFbx(v: Vec3): Vec3 {
  return [v[0], v[2], -v[1]];
}

function mul3x3(a: number[][], b: number[][]): number[][] {
  const out = [[0, 0, 0], [0, 0, 0], [0, 0, 0]];
  for (let i = 0; i < 3; i++)
    for (let j = 0; j < 3; j++)
      out[i][j] = a[i][0] * b[0][j] + a[i][1] * b[1][j] + a[i][2] * b[2][j];
  return out;
}

const R_ZUP_TO_YUP = [
  [1, 0, 0],
  [0, 0, 1],
  [0, -1, 0],
];

// Euler (deg, FBX eEulerXYZ / Blender 'XYZ': R = Rx·Ry·Rz) from a rotation
// matrix whose columns are the local axes.
function basisToEulerXYZ(m: number[][]): Vec3 {
  const sy = Math.max(-1, Math.min(1, m[0][2]));
  const ry = Math.asin(sy);
  let rx: number, rz: number;
  if (Math.abs(Math.cos(ry)) > 1e-6) {
    rx = Math.atan2(-m[1][2], m[2][2]);
    rz = Math.atan2(-m[0][1], m[0][0]);
  } else {
    rx = Math.atan2(m[2][1], m[1][1]);
    rz = 0;
  }
  const d = 180 / Math.PI;
  return [rx * d, ry * d, rz * d];
}

function computeVertexNormals(mesh: MeshData): Vec3[] {
  const n: Vec3[] = mesh.vertices.map(() => [0, 0, 0]);
  for (const f of mesh.faces) {
    const a = mesh.vertices[f[0]], b = mesh.vertices[f[1]], c = mesh.vertices[f[2]];
    const ux = b[0] - a[0], uy = b[1] - a[1], uz = b[2] - a[2];
    const vx = c[0] - a[0], vy = c[1] - a[1], vz = c[2] - a[2];
    const fn: Vec3 = [uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx];
    for (const idx of f) { n[idx][0] += fn[0]; n[idx][1] += fn[1]; n[idx][2] += fn[2]; }
  }
  return n.map((v) => {
    const l = Math.hypot(v[0], v[1], v[2]) || 1;
    return [v[0] / l, v[1] / l, v[2] / l] as Vec3;
  });
}

function f(n: number): string {
  return (Math.round(n * 1e6) / 1e6).toString();
}

function hexRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  return [parseInt(h.slice(0, 2), 16) / 255, parseInt(h.slice(2, 4), 16) / 255, parseInt(h.slice(4, 6), 16) / 255];
}

export function genFbx(project: TrackProject, built: BuiltTrack): string {
  let idSeq = 1000000;
  const nextId = () => ++idSeq;
  const pal = THEME_PALETTES[project.meta.theme];

  interface MeshNode { geomId: number; modelId: number; matId: number; mesh: MeshData; }
  const meshNodes: MeshNode[] = built.meshes.map((m) => ({
    geomId: nextId(), modelId: nextId(), matId: nextId(), mesh: m,
  }));
  interface NullNode { modelId: number; attrId: number; e: EmptyData; }
  const nullNodes: NullNode[] = built.empties.map((e) => ({ modelId: nextId(), attrId: nextId(), e }));

  const out: string[] = [];
  const L = (n: number, s: string) => out.push('\t'.repeat(n) + s);

  L(0, '; FBX 7.4.0 project file');
  L(0, '; Generated by AC Track Forge');
  L(0, '; ----------------------------------------------------');
  L(0, '');
  L(0, 'FBXHeaderExtension:  {');
  L(1, 'FBXHeaderVersion: 1003');
  L(1, 'FBXVersion: 7400');
  L(1, 'Creator: "AC Track Forge"');
  L(0, '}');
  L(0, 'GlobalSettings:  {');
  L(1, 'Version: 1000');
  L(1, 'Properties70:  {');
  L(2, 'P: "UpAxis", "int", "Integer", "",1');
  L(2, 'P: "UpAxisSign", "int", "Integer", "",1');
  L(2, 'P: "FrontAxis", "int", "Integer", "",2');
  L(2, 'P: "FrontAxisSign", "int", "Integer", "",1');
  L(2, 'P: "CoordAxis", "int", "Integer", "",0');
  L(2, 'P: "CoordAxisSign", "int", "Integer", "",1');
  L(2, 'P: "OriginalUpAxis", "int", "Integer", "",1');
  L(2, 'P: "UnitScaleFactor", "double", "Number", "",1');
  L(2, 'P: "OriginalUnitScaleFactor", "double", "Number", "",1');
  L(1, '}');
  L(0, '}');

  const objectCount = meshNodes.length * 3 + nullNodes.length * 2;
  L(0, 'Definitions:  {');
  L(1, 'Version: 100');
  L(1, `Count: ${objectCount}`);
  L(1, 'ObjectType: "GlobalSettings" {');
  L(2, 'Count: 1');
  L(1, '}');
  L(1, 'ObjectType: "Geometry" {');
  L(2, `Count: ${meshNodes.length}`);
  L(1, '}');
  L(1, 'ObjectType: "Model" {');
  L(2, `Count: ${meshNodes.length + nullNodes.length}`);
  L(1, '}');
  L(1, 'ObjectType: "Material" {');
  L(2, `Count: ${meshNodes.length}`);
  L(1, '}');
  L(1, 'ObjectType: "NodeAttribute" {');
  L(2, `Count: ${nullNodes.length}`);
  L(1, '}');
  L(0, '}');

  L(0, 'Objects:  {');
  for (const mn of meshNodes) {
    const verts = mn.mesh.vertices.map(toFbx);
    const norms = computeVertexNormals(mn.mesh).map(toFbx);
    const vFlat: string[] = [];
    for (const v of verts) vFlat.push(f(v[0]), f(v[1]), f(v[2]));
    const idx: string[] = [];
    for (const face of mn.mesh.faces) idx.push(String(face[0]), String(face[1]), String(-(face[2] + 1)));
    const nFlat: string[] = [];
    for (const nv of norms) nFlat.push(f(nv[0]), f(nv[1]), f(nv[2]));

    L(1, `Geometry: ${mn.geomId}, "Geometry::${mn.mesh.name}", "Mesh" {`);
    L(2, `Vertices: *${vFlat.length} {`);
    L(3, `a: ${vFlat.join(',')}`);
    L(2, '}');
    L(2, `PolygonVertexIndex: *${idx.length} {`);
    L(3, `a: ${idx.join(',')}`);
    L(2, '}');
    L(2, 'GeometryVersion: 124');
    L(2, 'LayerElementNormal: 0 {');
    L(3, 'Version: 102');
    L(3, 'Name: ""');
    L(3, 'MappingInformationType: "ByVertice"');
    L(3, 'ReferenceInformationType: "Direct"');
    L(3, `Normals: *${nFlat.length} {`);
    L(4, `a: ${nFlat.join(',')}`);
    L(3, '}');
    L(2, '}');
    L(2, 'LayerElementMaterial: 0 {');
    L(3, 'Version: 101');
    L(3, 'Name: ""');
    L(3, 'MappingInformationType: "AllSame"');
    L(3, 'ReferenceInformationType: "IndexToDirect"');
    L(3, 'Materials: *1 {');
    L(4, 'a: 0');
    L(3, '}');
    L(2, '}');
    L(2, 'Layer: 0 {');
    L(3, 'Version: 100');
    L(3, 'LayerElement:  {');
    L(4, 'Type: "LayerElementNormal"');
    L(4, 'TypedIndex: 0');
    L(3, '}');
    L(3, 'LayerElement:  {');
    L(4, 'Type: "LayerElementMaterial"');
    L(4, 'TypedIndex: 0');
    L(3, '}');
    L(2, '}');
    L(1, '}');

    L(1, `Model: ${mn.modelId}, "Model::${mn.mesh.name}", "Mesh" {`);
    L(2, 'Version: 232');
    L(2, 'Properties70:  {');
    L(3, 'P: "Lcl Translation", "Lcl Translation", "", "A",0,0,0');
    L(3, 'P: "Lcl Rotation", "Lcl Rotation", "", "A",0,0,0');
    L(3, 'P: "Lcl Scaling", "Lcl Scaling", "", "A",1,1,1');
    L(3, 'P: "DefaultAttributeIndex", "int", "Integer", "",0');
    L(2, '}');
    L(2, 'Shading: T');
    L(2, 'Culling: "CullingOff"');
    L(1, '}');

    const [r, g, b] = hexRgb(meshColor(mn.mesh.name, pal));
    L(1, `Material: ${mn.matId}, "Material::mat_${mn.mesh.name}", "" {`);
    L(2, 'Version: 102');
    L(2, 'ShadingModel: "lambert"');
    L(2, 'MultiLayer: 0');
    L(2, 'Properties70:  {');
    L(3, `P: "DiffuseColor", "Color", "", "A",${f(r)},${f(g)},${f(b)}`);
    L(3, `P: "Diffuse", "Vector3D", "Vector", "",${f(r)},${f(g)},${f(b)}`);
    L(3, 'P: "Emissive", "Vector3D", "Vector", "",0,0,0');
    L(2, '}');
    L(1, '}');
  }

  for (const nn of nullNodes) {
    const pos = toFbx(nn.e.position);
    const fbxBasis = mul3x3(R_ZUP_TO_YUP, nn.e.basis);
    const [rx, ry, rz] = basisToEulerXYZ(fbxBasis);
    L(1, `NodeAttribute: ${nn.attrId}, "NodeAttribute::", "Null" {`);
    L(2, 'TypeFlags: "Null"');
    L(1, '}');
    L(1, `Model: ${nn.modelId}, "Model::${nn.e.name}", "Null" {`);
    L(2, 'Version: 232');
    L(2, 'Properties70:  {');
    L(3, `P: "Lcl Translation", "Lcl Translation", "", "A",${f(pos[0])},${f(pos[1])},${f(pos[2])}`);
    L(3, `P: "Lcl Rotation", "Lcl Rotation", "", "A",${f(rx)},${f(ry)},${f(rz)}`);
    L(3, 'P: "Lcl Scaling", "Lcl Scaling", "", "A",1,1,1');
    L(2, '}');
    L(2, 'Shading: Y');
    L(2, 'Culling: "CullingOff"');
    L(1, '}');
  }
  L(0, '}');

  L(0, 'Connections:  {');
  for (const mn of meshNodes) {
    L(1, `C: "OO",${mn.modelId},0`);
    L(1, `C: "OO",${mn.geomId},${mn.modelId}`);
    L(1, `C: "OO",${mn.matId},${mn.modelId}`);
  }
  for (const nn of nullNodes) {
    L(1, `C: "OO",${nn.modelId},0`);
    L(1, `C: "OO",${nn.attrId},${nn.modelId}`);
  }
  L(0, '}');
  L(0, '');

  return out.join('\n');
}
