import type { TrackProject } from '../types';
import type { BuiltTrack } from '../geometry';

interface TexInfo { surface: string; name: string }

// Tailored manual-steps doc, with the real track name baked in. Primary flow is
// now: import the provided FBX into KsEditor, export KN5, drop into AC.
export function genInstructions(
  project: TrackProject,
  built: BuiltTrack,
  slug: string,
  textures: TexInfo[] = [],
): string {
  const texMap = textures
    .map((t) => `   - \`mat_${t.surface}\` → shader **ksPerPixel**, txDiffuse = \`texture/${t.name}\``)
    .join('\n');
  const pitboxes = built.empties.filter((e) => e.name.startsWith('AC_PIT_')).length;
  const surfaces = [...new Set(built.meshes.map((m) => m.name))].join(', ');
  const closureWarn = built.closure.closed
    ? ''
    : `\n> ⚠️ **Closure warning:** start/finish is discontinuous ` +
      `(gap ${built.closure.gap.toFixed(1)} m, heading off ${built.closure.headingOff.toFixed(0)}°). ` +
      `Use **Close loop** in the editor before exporting for a clean lap.\n`;
  const bridgeNote =
    project.bridge.auto && built.overlaps.length > 0
      ? `\n> 🌉 ${built.overlaps.length} self-crossing(s) were turned into overpasses automatically.\n`
      : '';

  return `# ${project.meta.name} — build instructions

Generated by **AC Track Forge**. Track folder name: \`${slug}\`
Length: ~${Math.round(built.totalLength)} m · Pit boxes: ${pitboxes} · Surfaces: ${surfaces}
${closureWarn}${bridgeNote}
Folder/file names must stay **lowercase, no spaces, no special characters** — use \`${slug}\`.

The mesh in \`${slug}.fbx\` is already correct: 1:1 scale, normals up, one surface keyword
per object (${surfaces}), a coloured material assigned to every mesh, and the \`AC_*\`
spawn/timing objects oriented (+Z = travel, +Y = up, scale 1, ~1 m above the surface).
${built.meshes.some((m) => m.name.startsWith('DECOR')) ? '\n`DECOR_*` meshes (flag, grandstands, arch) are **visual-only** — no surface prefix, so AC gives them no collision.\n' : ''}

---

## A. Compile to KN5 (KsEditor) — the only required step

Placeholder textures are included in the \`texture/\` folder (one solid colour per surface).
Keep that folder next to \`${slug}.fbx\` when you import.

1. Open **KsEditor** (\`assettocorsa/sdk/editor/\`). **File → Import FBX** → choose \`${slug}.fbx\`.
   - Navigation: hold **left mouse** to look, **arrow keys** to move, **Ctrl** faster,
     **Shift** slower, **right-click** to select.
2. **Assign a shader to each material** (Materials tab → click the material → set **Shader =
   ksPerPixel** → set **txDiffuse** to the matching PNG). Materials render black until you do this:
${texMap}
   - (If the track looks rotated/mis-scaled, that's the FBX axis/scale knob — re-export or use
     the Blender fallback below.)
3. **Save** (writes the persistence \`.ini\`) → **Export KN5** → name it \`${slug}.kn5\`.

## B. Install into Assetto Corsa

1. In \`assettocorsa/content/tracks/\` create a folder named \`${slug}\` (lowercase, no spaces).
2. Put \`${slug}.kn5\` **directly inside** it.
3. Add the provided \`ui/ui_track.json\` and \`data/surfaces.ini\`, plus an empty \`ai/\` folder.
   Do **not** nest the track folder inside extra folders.

   \`\`\`
   content/tracks/${slug}/
     ${slug}.kn5
     ui/ui_track.json
     data/surfaces.ini
     ai/            (empty for now)
   \`\`\`
4. **Test in Practice first.** AC → Drive → Practice → select the track. Practice only needs
   \`AC_PIT_0\` and no AI line, so it's the cleanest first test.
5. If it loads and you can drive without falling through — success. Then add extras (AI fast
   lane recorded in-game, cameras) one at a time, re-testing. Logs: \`Documents/Assetto Corsa/logs/\`.

## Fallback: rebuild the FBX in Blender

If KsEditor dislikes the FBX, open \`blender_fallback/build_track.py\` in Blender
(Scripting → Run). It rebuilds the identical geometry and re-exports \`${slug}.fbx\` using
Blender's own exporter.

---

### Correctness checklist (already satisfied by the export)
- [x] Meshes at exactly 1:1 scale, scale applied
- [x] Face normals point up — track visible/solid from above
- [x] Physical meshes adjacent, never overlapping
- [x] Mesh names one keyword each: ${surfaces}
- [x] Materials assigned to every mesh (no unassigned/black surfaces)
- [x] Spawn/timing empties: +Z = travel, +Y = up, scale 1, ~1 m above surface
- [x] \`ui_track.json\` pitboxes (${pitboxes}) == number of \`AC_PIT_*\` objects
- [x] Folder + file names lowercase, no spaces/special characters, not double-nested
`;
}
