// Paste-a-sheet track builder. Drop in a list of commands (hand-written, or
// generated by an AI from the spec) and the app builds the circuit from it.
// The spec is copyable straight out of here so you can hand it to any AI.
import { useState } from 'react';
import type { TrackProject } from '../types';
import { INSTRUCTION_SPEC, applyInstructions } from '../state/instructions';

export function InstructionsPanel({
  project, onBuild, onClose,
}: {
  project: TrackProject;
  onBuild: (p: TrackProject) => void;
  onClose: () => void;
}) {
  const [text, setText] = useState('');
  const [result, setResult] = useState<{ log: string[]; errors: string[]; applied: number } | null>(null);
  const [copied, setCopied] = useState('');

  const preview = () => {
    const r = applyInstructions(project, text);
    setResult({ log: r.log, errors: r.errors, applied: r.applied });
    return r;
  };
  const build = () => {
    const r = preview();
    if (r.applied > 0) onBuild(r.project);
  };
  const copy = async (what: 'spec' | 'example', value: string) => {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(what);
      setTimeout(() => setCopied(''), 1600);
    } catch { /* clipboard unavailable — the text is selectable anyway */ }
  };

  return (
    <div className="prompt-overlay" onMouseDown={onClose}>
      <div className="instr-box" onMouseDown={(e) => e.stopPropagation()}>
        <div className="instr-head">
          <b>Build from an instruction sheet</b>
          <button className="small" onClick={onClose}>close</button>
        </div>
        <div className="muted instr-intro">
          Paste a list of commands and the app builds the circuit. Give the spec below to any
          AI (“write me a 4 km circuit using this format”) and paste back what it writes.
        </div>

        <div className="instr-actions">
          <button className="small" onClick={() => copy('spec', INSTRUCTION_SPEC)}>
            {copied === 'spec' ? '✓ copied' : '📋 Copy spec for AI'}
          </button>
          <button className="small" onClick={() => setText(EXAMPLE)}>Load example</button>
          <span className="spacer" />
          <button className="small" onClick={preview} disabled={!text.trim()}>Check</button>
          <button className="primary" onClick={build} disabled={!text.trim()}>Build track</button>
        </div>

        <textarea
          className="instr-text"
          placeholder={'NAME My Circuit\nPRESET modern_gp\nCLEAR\nSTRAIGHT 800\nCORNER right 50 90\n...'}
          value={text}
          onChange={(e) => { setText(e.target.value); setResult(null); }}
          spellCheck={false}
        />

        {result && (
          <div className="instr-result">
            <div className={result.errors.length ? 'instr-warn' : 'instr-ok'}>
              {result.applied} command{result.applied === 1 ? '' : 's'} applied
              {result.errors.length > 0 && ` · ${result.errors.length} line${result.errors.length === 1 ? '' : 's'} skipped`}
            </div>
            {result.errors.length > 0 && (
              <ul className="instr-errs">{result.errors.map((e, i) => <li key={i}>{e}</li>)}</ul>
            )}
            {result.log.length > 0 && (
              <details>
                <summary className="muted">what it did ({result.log.length})</summary>
                <ul className="instr-log">{result.log.map((l, i) => <li key={i}>{l}</li>)}</ul>
              </details>
            )}
          </div>
        )}

        <details className="instr-spec">
          <summary>Command reference (this is what you give the AI)</summary>
          <pre>{INSTRUCTION_SPEC}</pre>
        </details>
      </div>
    </div>
  );
}

const EXAMPLE = `# A quick 3-corner circuit — edit freely
NAME Riverside Park
AUTHOR ${'me'}
PRESET modern_gp
WIDTH 13

CLEAR
STRAIGHT 850
CORNER right 45 90
STRAIGHT 300
CORNER left 80 120
STRAIGHT 220
CORNER right 60 90
STRAIGHT 400
CORNER right 35 60
STRAIGHT 180

ESCAPE 0 gravel
CORNERKERB 1 flat combo flat
PITLANE 60 400 12
PITBOXES 24
LIGHTS 80
`;
